export const VOTER_TYPES = {
    SET_VOTER_FORM: 'SET_VOTER_FORM',
    RESET_VOTER_FORM: 'RESET_VOTER_FORM',
    UPDATE_VOTER_INFO: 'UPDATE_VOTER_INFO',
    VOTER_LOGIN: "VOTER_LOGIN",
    VOTER_LOGOUT: "VOTER_LOGOUT"
}